# Generated by Django 6.0.4 on 2026-05-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_navigationmenu_navigationmenulink'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenu',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='navigationmenu',
            constraint=models.UniqueConstraint(fields=('locale', 'slug'), name='navigationmenu_locale_slug_uniq'),
        ),
    ]
